**Importing The Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Importing the dataset**


In [ ]:
dataset = pd.read_csv('Data.csv')

**I M P U T A T I O N**

Finding Missing Value


In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Housearea               29 non-null     float64
 1   bedroom                 29 non-null     int64  
 2   storey                  29 non-null     int64  
 3   parking                 26 non-null     float64
 4   gardenarea              29 non-null     float64
 5   nearestrailwaystation   29 non-null     float64
 6   crimerate               29 non-null     float64
 7   price                   26 non-null     float64
dtypes: float64(6), int64(2)
memory usage: 1.9 KB


In [ ]:
dataset.isnull()

Housearea  bedroom  storey  ...  nearestrailwaystation   crimerate  price
0       False    False   False  ...                   False      False  False
1       False    False   False  ...                   False      False  False
2       False    False   False  ...                   False      False  False
3       False    False   False  ...                   False      False  False
4       False    False   False  ...                   False      False  False
5       False    False   False  ...                   False      False  False
6       False    False   False  ...                   False      False   True
7       False    False   False  ...                   False      False  False
8       False    False   False  ...                   False      False  False
9       False    False   False  ...                   False      False  False
10      False    False   False  ...                   False      False  False
11      False    False   False  ...                   False      False  False
12      False    False   False  ...                   False      False  False
13      False    False   False  ...                   False      False   True
14      False    False   False  ...                   False      False  False
15      False    False   False  ...                   False      False  False
16      False    False   False  ...                   False      False  False
17      False    False   False  ...                   False      False   True
18      False    False   False  ...                   False      False  False
19      False    False   False  ...                   False      False  False
20      False    False   False  ...                   False      False  False
21      False    False   False  ...                   False      False  False
22      False    False   False  ...                   False      False  False
23      False    False   False  ...                   False      False  False
24      False    False   False  ...                   False      False  False
25      False    False   False  ...                   False      False  False
26      False    False   False  ...                   False      False  False
27      False    False   False  ...                   False      False  False
28      False    False   False  ...                   False      False  False

[29 rows x 8 columns]

Price Imputation

In [ ]:
price_mean=dataset['price'].mean()

In [ ]:
price_mean

2812635.4138461533

In [ ]:
dataset['price'].fillna(price_mean,inplace=True)

Parking Lot Imputation

In [ ]:
dataset['parking'].value_counts()

1.0    20
0.0     6
Name: parking, dtype: int64

In [ ]:
dataset['parking'].fillna(1,inplace=True)

Location Imputation

to be used later:  
dataset['location'].value_counts()  
dataset['location'].fillna('kolkata',inplace=True)

Testing for any remaining imputation

In [ ]:
dataset.isnull()

Housearea  bedroom  storey  ...  nearestrailwaystation   crimerate  price
0       False    False   False  ...                   False      False  False
1       False    False   False  ...                   False      False  False
2       False    False   False  ...                   False      False  False
3       False    False   False  ...                   False      False  False
4       False    False   False  ...                   False      False  False
5       False    False   False  ...                   False      False  False
6       False    False   False  ...                   False      False  False
7       False    False   False  ...                   False      False  False
8       False    False   False  ...                   False      False  False
9       False    False   False  ...                   False      False  False
10      False    False   False  ...                   False      False  False
11      False    False   False  ...                   False      False  False
12      False    False   False  ...                   False      False  False
13      False    False   False  ...                   False      False  False
14      False    False   False  ...                   False      False  False
15      False    False   False  ...                   False      False  False
16      False    False   False  ...                   False      False  False
17      False    False   False  ...                   False      False  False
18      False    False   False  ...                   False      False  False
19      False    False   False  ...                   False      False  False
20      False    False   False  ...                   False      False  False
21      False    False   False  ...                   False      False  False
22      False    False   False  ...                   False      False  False
23      False    False   False  ...                   False      False  False
24      False    False   False  ...                   False      False  False
25      False    False   False  ...                   False      False  False
26      False    False   False  ...                   False      False  False
27      False    False   False  ...                   False      False  False
28      False    False   False  ...                   False      False  False

[29 rows x 8 columns]

Dividing the dataset

In [ ]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


In [ ]:
dataset.head()

Housearea  bedroom  storey  ...  nearestrailwaystation   crimerate       price
0    2523.40        4       2  ...                     0.5       0.23  2427850.00
1    2102.26        3       1  ...                     0.8       0.01  2837000.00
2    1850.27        2       2  ...                     0.8       0.20  2756280.26
3    2780.50        4       2  ...                     0.5       0.33  2375800.00
4    2180.02        3       1  ...                     0.4       0.05  3208900.00

[5 rows x 8 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Housearea               29 non-null     float64
 1   bedroom                 29 non-null     int64  
 2   storey                  29 non-null     int64  
 3   parking                 29 non-null     float64
 4   gardenarea              29 non-null     float64
 5   nearestrailwaystation   29 non-null     float64
 6   crimerate               29 non-null     float64
 7   price                   29 non-null     float64
dtypes: float64(6), int64(2)
memory usage: 1.9 KB


**we will test OneHotEncoder on this dataset**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers=[('cat',OneHotEncoder(),[7])],remainder='passthrough')
x =np.array(ct.fit_transform(x))


ValueError: ignored

In [ ]:
print(x)

[[2.52340e+03 4.00000e+00 2.00000e+00 1.00000e+00 2.56000e+02 5.00000e-01
  2.30000e-01]
 [2.10226e+03 3.00000e+00 1.00000e+00 0.00000e+00 3.10250e+02 8.00000e-01
  1.00000e-02]
 [1.85027e+03 2.00000e+00 2.00000e+00 0.00000e+00 1.25240e+02 8.00000e-01
  2.00000e-01]
 [2.78050e+03 4.00000e+00 2.00000e+00 1.00000e+00 3.60500e+02 5.00000e-01
  3.30000e-01]
 [2.18002e+03 3.00000e+00 1.00000e+00 1.00000e+00 2.60200e+02 4.00000e-01
  5.00000e-02]
 [2.62760e+03 4.00000e+00 2.00000e+00 1.00000e+00 3.40600e+02 7.50000e-01
  7.00000e-02]
 [3.12067e+03 4.00000e+00 2.00000e+00 1.00000e+00 4.20360e+02 6.40000e-01
  1.20000e-01]
 [1.68026e+03 2.00000e+00 1.00000e+00 0.00000e+00 2.10350e+02 4.00000e-01
  3.30000e-01]
 [2.12026e+03 3.00000e+00 1.00000e+00 0.00000e+00 3.30300e+02 6.50000e-01
  7.50000e-01]
 [2.18020e+03 4.00000e+00 2.00000e+00 1.00000e+00 2.50000e+02 4.00000e-01
  2.00000e-02]
 [1.56035e+03 3.00000e+00 1.00000e+00 0.00000e+00 2.10000e+02 6.00000e-01
  3.00000e-02]
 [1.97020e+03 2.00000

**split the data into training set and test set**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(*x_test, sep='\n')

[1.12222e+03 2.00000e+00 1.00000e+00 0.00000e+00 1.56000e+02 4.60000e-01
 3.00000e-02]
[2.248e+03 3.000e+00 2.000e+00 1.000e+00 2.205e+02 5.600e-01 5.000e-02]
[2.460e+03 3.000e+00 2.000e+00 1.000e+00 2.406e+02 3.500e-01 2.000e-02]
[2.75e+03 4.00e+00 2.00e+00 1.00e+00 2.85e+02 4.20e-01 1.10e-01]
[2.8700e+03 4.0000e+00 2.0000e+00 1.0000e+00 2.6052e+02 4.3000e-01
 3.0000e-02]
[2.68e+03 4.00e+00 2.00e+00 1.00e+00 2.70e+02 3.80e-01 3.00e-02]


In [ ]:
print(*y_test, sep='\n')

2448899.0
2555750.0
2685400.0
3546310.0
2784500.0
2845620.5


**training the data**

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**testing the data**

In [ ]:
test = regressor.predict(x_test)
print(*test, sep='\n')

2525956.0329060135
3065150.201058605
3196270.2585251946
3035026.38984161
3153270.147032555
3102899.7153100413


**Testing data manually**

In [ ]:
print(*y_test, sep='\n')

2448899.0
2555750.0
2685400.0
3546310.0
2784500.0
2845620.5


In [ ]:
pred_arr=[[3000,3,3,1,300,0.8,0.01,]]
test2=regressor.predict(pred_arr)
print(test2)

[3565324.93402638]


Plotting a line graph 

In [ ]:
plt.plot(,y_test,color="red")
plt.plot()
plt.title("predicted value vs actual value")
plt.show()

SyntaxError: ignored

In [ ]:
import pickle

In [ ]:
with open('model.pkl','wb') as f:
    pickle.dump(regressor,f)

In [ ]:
model=pickle.load(open('model.pkl', 'rb'))